import { describe, expect, test } from "vitest";

import "../../viewer/node-types/default-node-types";

import { exportGraphJson, importGraphJson } from "./graph-io";
import { CURRENT_GRAPH_VERSION } from "../../viewer/core/graph-migrations";
import { GuideTraversalEngine } from "../../viewer/core/guide-traversal-engine";
import { toStepViewModel } from "../../runtime/step-view-model";

// Frozen, real flows. They are NOT regenerated by tooling — they are
// deliberately immutable artefacts. If anyone removes or renames a node type
// without a migration these fail, regardless of what anyone remembered. That is
// the guard that cannot be forgotten.
const rawLegacyGuide = Object.values(
  import.meta.glob("../../viewer/core/__fixtures__/legacy-guide-v1.json", {
    query: "?raw",
    import: "default",
    eager: true,
  })
)[0] as string;

describe("golden: old flows", () => {
  test("the frozen fixture is unversioned (genuinely legacy)", () => {
    expect((JSON.parse(rawLegacyGuide) as { version?: number }).version).toBeUndefined();
  });

  test("an old flow loads, migrates and traverses unchanged", () => {
    const imported = importGraphJson(rawLegacyGuide);
    expect(imported.success).toBe(true);
    if (!imported.success) return;

    // The migration tagged the source language on title and option labels.
    const resident = imported.graph.nodes.find((node) => node.id === "q-resident");
    expect(resident?.data.title).toEqual({
      sv: "Är du folkbokförd i kommunen?",
    });
    const options = resident?.data.options as Array<{ label: unknown }>;
    expect(options[0]?.label).toEqual({ sv: "Ja" });

    const engine = new GuideTraversalEngine(imported.graph);
    expect(engine.getCurrentNode()?.id).toBe("q-resident");

    engine.answer("resident-yes");
    expect(engine.getCurrentNode()?.id).toBe("q-adult");

    engine.answer("adult-yes");
    expect(engine.getCurrentNode()?.id).toBe("result-approve");
    expect(engine.getAnswers()).toEqual({ resident: "yes", adult: "yes" });
  });

  test("the migrated map-form title resolves to source text in the view model", () => {
    const imported = importGraphJson(rawLegacyGuide);
    expect(imported.success).toBe(true);
    if (!imported.success) return;

    const engine = new GuideTraversalEngine(imported.graph);
    const viewModel = toStepViewModel(
      engine.getCurrentNode()!,
      engine.getAnswers(),
      imported.graph,
      { stepNumber: engine.getStepNumber(), canGoBack: engine.canGoBack() }
    );

    // The client gets a plain string, never the map object.
    expect(viewModel.kind).toBe("choice");
    if (viewModel.kind === "unsupported") return;
    expect(viewModel.title).toBe("Är du folkbokförd i kommunen?");
  });

  test("the shorter path leads to a rejection", () => {
    const imported = importGraphJson(rawLegacyGuide);
    expect(imported.success).toBe(true);
    if (!imported.success) return;

    const engine = new GuideTraversalEngine(imported.graph);
    engine.answer("resident-no");
    expect(engine.getCurrentNode()?.id).toBe("result-reject");
  });

  test("a migrated graph is exported stamped with the current version", () => {
    const imported = importGraphJson(rawLegacyGuide);
    expect(imported.success).toBe(true);
    if (!imported.success) return;

    const exported = exportGraphJson(imported.graph);
    expect(exported.success).toBe(true);
    if (!exported.success) return;

    expect((JSON.parse(exported.json) as { version?: number }).version).toBe(
      CURRENT_GRAPH_VERSION
    );
  });
});
